## DO NOT ALTER -- CONFIGURED TO USE .ENV ##

# Generic configuration for Alembic
[alembic]
# Location for migration scripts
script_location = alembic

# Adds current dir to sys.path to find app modules
prepend_sys_path = .

# Version path separator (OS default)
version_path_separator = os

# Automatically using DATABASE_URL from pydantic settings
sqlalchemy.url = driver://usuario:senha@localhost/nome_do_banco

[post_write_hooks]
# Post write hooks

# Log settings
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
