## !! NÃO ALTERAR -- ESTÁ CONFIGURADO PARA USAR O ARQUIVO .ENV !! ##

# Configuração genérica do Alembic
[alembic]
# Localização dos scripts de migração
script_location = alembic

# Adiciona o diretório atual ao sys.path para encontrar os módulos do app
prepend_sys_path = .

# Separador de caminho de versão (padrão do sistema operacional)
version_path_separator = os

# A URL abaixo é ignorada pois o arquivo alembic/env.py está configurado
# para usar as definições do arquivo .env via Pydantic (config.py)
sqlalchemy.url = driver://usuario:senha@localhost/nome_do_banco

[post_write_hooks]
# Ganchos de pós-escrita (opcional, como formatadores de código)

# Configurações de Log
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
